### ISSUE TITLE
Episode 13: TypeError Cannot read property component

### ISSUE THREAD

**Issue by edalee** [cassiozen/ReactCasts#67]
Express server error.  
Ubuntu 17.10.

Hi Cassiozen, 

I'm very much enjoying your SSR series. 

However, I seem to get an annoying _TypeError_ on all routes when fetching the `requestInitialData` . As you will see below, it states that it can not find the route's component -- yet it does display the data on the page and the route object has a component. Therefore, I'm a little confused at why I'm seeing this error. Eslint also states the Promise is not declared, however, I think this is not related -- right?  

Any help would be very much appreciated!

Thanks
/ Ed

**node error:**
```
   TypeError: Cannot read property 'component' of undefined
    at /home/edward/Development/React_Dev/Universal_React_template/webpack:/src/server/index.js:130:1
    at Layer.handle [as handle_request] (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/layer.js:95:5)
    at /home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/index.js:281:22
    at param (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/index.js:354:14)
    at param (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/index.js:410:3)
    at next (/home/edward/Development/React_Dev/Universal_React_template/node_modules/express/lib/router/index.js:275:10)
```
**Package Json**
```
{
  "name": "node",
  "version": "1.0.0",
  "description": "Basic server-side rendering",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start-dev": "NODE_ENV=development webpack -w & NODE_ENV=development node server.js"
  },
  "author": "Edward Lee",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^8.4.1",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.1",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.9",
    "eslint": "^4.17.0",
    "eslint-plugin-react": "^7.6.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "helmet-webpack-plugin": "^0.0.3",
    "nodemon": "^1.17.3",
    "postcss-loader": "^2.1.0",
    "prop-types": "^15.6.0",
    "webpack": "^3.10.0",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "cors": "^2.8.4",
    "express": "^4.16.2",
    "isomorphic-fetch": "^2.2.1",
    "lodash.orderby": "^4.6.0",
    "node-time-ago": "^1.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2",
    "source-map-support": "^0.5.5"
  }
}
```
**webpack Server Conf:**
```
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const autoprefixer = require('autoprefixer');
const nodeExternals = require('webpack-node-externals');

const serverConfig = {
    entry: './src/server/index.js',
    target: 'node',
    externals: [nodeExternals()],
    output: {
        path: __dirname,
        filename: 'server.js',
        libraryTarget: 'commonjs2'
    },
    devtool: 'cheap-module-source-map',
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                loader: 'babel-loader',
                query: {
                    presets: ["react"]
                }
            },
            {
                test: /\.css$/,
                use: [
                    'css-loader/locals',
                ]
            },
            {
                test: /\.(png|svg|jpg|gif)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: 'public/img/[name].[ext]',
                            publicPath: url => url.replace(/public/, ''),
                            emit: false
                        }
                    }
                ]
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                use: [
                    'file-loader'
                ]
            }
        ]
    },
    plugins: [
        new webpack.BannerPlugin({
          banner: "__isBrowser__ = false;",
          raw: true,
          include: /\.js$/
        })
    ]
};

```

**Comment by IniterWorker** [comment]
I guess it's because this part isn't safety.

```js
const activeRoute = routes.find(route => matchPath(req.url, route));
    const requestInitialData =
        activeRoute.component.requestInitialData
        && activeRoute.component.requestInitialData();
```

I think if you look up with the `console.log(req.url)` you will see a bad file or bad route used to call another element.

It's an architectural mistake :-)
